name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: make ci
      - uses: actions/upload-artifact@v3
        with:
          path: ./icu4c-wasi.tar.xz
          name: icu4c-wasi.tar.xz
      - name: Create new release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: gh release create "$GITHUB_REF_NAME" icu4c-wasi.tar.xz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
