name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: ci-build
        run: ./ci-build.sh
      - uses: actions/upload-artifact@v3
        with:
          path: ./icu4c-wasi.tar.xz
          name: icu4c-wasi.tar.xz
