name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: env GNUMAKEFLAGS=-j$((1 + $(nproc --all))) make ci
      - uses: actions/upload-artifact@v4
        with:
          path: ./icu4c-wasm32-unknown-wasi.tar.xz
          name: icu4c-wasm32-unknown-wasi.tar.xz
      - uses: actions/upload-artifact@v4
        with:
          path: ./icu4c-wasm32-unknown-wasip1-threads.tar.xz
          name: icu4c-wasm32-unknown-wasip1-threads.tar.xz
      - name: Create new release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: gh release create "$GITHUB_REF_NAME" icu4c-wasm32-unknown-wasi.tar.xz icu4c-wasm32-unknown-wasip1-threads.tar.xz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
