name: Release
on: push
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: ci-build
        run: ./ci-build.sh
      - uses: actions/upload-artifact@v1
        with:
          path: ./icu4c-wasi.tar.xz
          name: icu4c-wasi.tar.xz
